name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push en la rama 'main'
  pull_request:
    branches:
      - main  # Se ejecuta en pull requests hacia la rama 'main'

jobs:
  # Etapa de construcción (build)
  build:
    runs-on: ubuntu-latest  # Utiliza la última versión de Ubuntu para ejecutar el trabajo
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2  # Clona el código del repositorio

    - name: Set up JDK 11
      uses: actions/setup-java@v2  # Configura Java en la versión 11
      with:
        java-version: '11'  # Utiliza JDK 11
        distribution: 'adoptopenjdk'  # Distribución de OpenJDK (ahora Adoptium)

    - name: Cache Maven dependencies
      uses: actions/cache@v2  # Utiliza caching para acelerar la instalación de dependencias
      with:
        path: ~/.m2/repository  # Ruta donde se almacenan las dependencias de Maven
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Usa un hash del archivo pom.xml como clave para el caché
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install  # Ejecuta Maven para construir el proyecto

  # Etapa de pruebas (test)
  test:
    runs-on: ubuntu-latest
    needs: build  # Depende de la etapa 'build'

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Run tests with Maven
      run: mvn test  # Ejecuta las pruebas unitarias con Maven

  # Etapa de despliegue (deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Depende de la etapa 'test'
    if: success()  # Solo se ejecuta si las pruebas fueron exitosas

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Deploy the application
      run: |
        echo "Desplegando la aplicación..."
        # Aquí puedes agregar el código necesario para el despliegue
        # Por ejemplo, empaquetar el proyecto en un archivo JAR
        mvn package
